pull_request_rules:
  - name: assign PRs with java files modified to hasnainmakada-99
    conditions:
      - files~=\.java$
    actions:
      assign:
        add_users:
          - hasnainmakada-99
